<?xml version="1.0" ?>
<robot name="angsa_heron" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="wheel_radius" value="0.140" />
  <xacro:property name="wheel_separation" value="0.616" />

  <link name="base_footprint"/>

  <link name="wheel_left_link">
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="1.0"/>
        <inertia ixx="0.008" ixy="0.0" ixz="0.0"
                  iyy="0.015" iyz="0.0"
                  izz="0.020" />
        </inertial>
  </link>
  <joint name="wheel_left_joint" type="continuous">
      <parent link="base_footprint"/>
      <child link="wheel_left_link"/>
      <origin xyz="0.0 ${wheel_separation/2} ${wheel_radius}" rpy="-1.57 0 0"/>
      <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_right_link">
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="1.0"/>
        <inertia ixx="0.008" ixy="0.0" ixz="0.0"
                  iyy="0.015" iyz="0.0"
                  izz="0.020" />
        </inertial>
  </link>
  <joint name="wheel_right_joint" type="continuous">
      <parent link="base_footprint"/>
      <child link="wheel_right_link"/>
      <origin xyz="0.0 ${-wheel_separation/2} ${wheel_radius}" rpy="-1.57 0 0"/>
      <axis xyz="0 0 1"/>
  </joint>

  <ros2_control name="Loopback" type="system">
      <hardware>
        <plugin>mock_components/GenericSystem</plugin>
        <param name="mock_sensor_commands">false</param>
        <param name="state_following_offset">0.0</param>
        <param name="calculate_dynamics">true</param>
      </hardware>
      <joint name="wheel_left_joint">
        <command_interface name="velocity">
          <param name="initial_value">0.0</param>
        </command_interface>
        <state_interface name="velocity">
          <param name="initial_value">0.0</param>
        </state_interface>
        <state_interface name="position">
          <param name="initial_value">0.0</param>
        </state_interface>
      </joint>
      <joint name="wheel_right_joint">
        <command_interface name="velocity">
          <param name="initial_value">0.0</param>
        </command_interface>
        <state_interface name="velocity">
          <param name="initial_value">0.0</param>
        </state_interface>
        <state_interface name="position">
          <param name="initial_value">0.0</param>
        </state_interface>
      </joint>
  </ros2_control>


</robot>
