bt_navigator:
  ros__parameters:
    default_nav_through_poses_bt_xml: /home/angsa/underlay_ws/src/planner_playground/config/test_navigation.xml

controller_server:
  ros__parameters:
    progress_checker:
      movement_time_allowance: 0.1

planner_server:
  ros__parameters:
    SMAC:
      debug_visualizations: True

local_costmap:
  local_costmap:
    ros__parameters:
      plugins:
        - 'inflation_layer'

global_costmap:
  global_costmap:
    ros__parameters:
      plugins:
        - 'inflation_layer'