bt_navigator:
  ros__parameters:
    default_nav_through_poses_bt_xml: /home/angsa/underlay_ws/src/planner_playground/config/test_navigation.xml

planner_server:
  ros__parameters:
    SMAC:
      debug_visualizations: True

local_costmap:
  local_costmap:
    ros__parameters:
      # plugins:
      #   - 'inflation_layer'
      static_layer_geofence:
        map_topic: /map_amcl
        footprint_clearing_enabled: false

global_costmap:
  global_costmap:
    ros__parameters:
      # plugins:
      #   - 'inflation_layer'
      static_layer_geofence:
        map_topic: /map_amcl
        footprint_clearing_enabled: false